# Generated by Django 3.0.3 on 2020-02-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200220_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
